- platform: bayesian
  prior: 0.33
  name: 'Everybody in Bed'
  probability_threshold: 0.9 
  observations:
      - entity_id: 'group.tracked_users'
        prob_given_true: 0.99
        prob_given_false: 0.45 
        platform: 'state'
        to_state: 'home'
      - entity_id: 'sensor.sun'
        prob_given_true: 0.9 
        prob_given_false: 0.2 
        platform: 'state'
        to_state: 'below_horizon'
      - entity_id: 'group.all_lights'
        prob_given_true: 0.99 
        prob_given_false: 0.5 
        platform: 'state'
        to_state: 'off'
      - entity_id: 'remote.living_room'
        prob_given_true: 0.99 
        prob_given_false: 0.7
        platform: 'state'
        to_state: 'off'
      - platform: 'numeric_state'
        entity_id: 'sensor.pixel_3_battery'                                                                                                                                         
        prob_given_true: 0.8
        prob_given_false: .2
        above: 95
        #      - entity_id: 'variable.last_motion'
        # prob_given_true: 0.9
        # prob_given_false: 0.3
        # platform: 'state'
        # to_state: 'Bathroom Motion'
        # - entity_id: 'binary_sensor.brad_phone_pluggedin'
        # prob_given_true: 0.95
        # prob_given_false: 0.5
        # platform: 'state'
        # to_state: 'on'
