homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 42.3453
  longitude: -83.8244
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 265
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Detroit
  # Customization file
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

device_tracker:
  - platform: nmap_tracker
    hosts: 
      - 192.168.0.31
      - 192.168.0.30

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:3218

python_script:

# Sensors
sensor:
  # Weather prediction
  - platform: yr
  - platform: template
    sensors:
      sun_elevation:
        value_template: "{{states.sun.sun.attributes.elevation}}"
      sun_is_rising: 
        value_template: "{{states.sun.sun.attributes.rising}}"
      pixel_3_battery:
          value_template: "{{ states.device_tracker.pixel_3.attributes.battery }}"
          friendly_name: "Pixel 3 Battery Level"

remote:
  - platform: harmony
    name: Living Room
    host: 192.168.0.90
    activity: Watch TV
  - platform: harmony
    name: Basement
    host: 192.168.0.91
    activity: Watch TV

#lutron_caseta:
#    host: 192.168.0.100
#    keyfile: /ssl/lutron/caseta.key
#    certfile: /ssl/lutron/caseta.crt
#    ca_certs: /ssl/lutron/caseta-bridge.crt
    
lutron_caseta_pro:
    bridges:
      - host: 192.168.0.100
        mac: F4:5E:AB:33:68:93

tplink:
  discovery: false
  switch:
    - host: 192.168.0.60
    - host: 192.168.0.61
    - host: 192.168.0.62
    - host: 192.168.0.63
#    - host: 192.168.0.64
#    - host: 192.168.0.66
#  strip:
#    - host: 192.168.0.65

media_player:
  - platform: spotify
    client_id: 8015cfb9d68b4fa89850c17ab22c3f24
    client_secret: c3ea3d29c2bd4e0b9cda8581a7718ada
#    aliases:
#        abc123def456: 'Kitchen'

dyson:
  username: mcochran@gmail.com
  password: fGsltw41!
  language: US
  devices:
    - device_id: C2Z-US-MBC8629A
      device_ip: 192.168.0.241


# googlehome:
#   devices:
#     - host: 192.168.0.107
#     - host: 192.168.0.108
#     - host: 192.168.0.109

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    
rest_command:
  assistant_broadcast:
    url: http://192.168.0.118:3000/assistant
    method: POST
    content_type: 'application/json'
    payload: '{"command":"{{ command }}", "user":"mcochran", "broadcast":true}'
    
  assistant_converse:
    url: http://192.168.0.118:3000/assistant
    method: POST
    content_type: 'application/json'
    payload: '{"command":"{{ command }}", "user":"mcochran", "converse":true}'

  assistant_relay:
    url: http://192.168.0.118:3000/assistant
    method: POST
    content_type: 'application/json'
    payload: '{"command":"{{ command }}", "user":"mcochran"}'

group: !include groups.yaml
automation: !include automations.yaml
binary_sensor: !include binary_sensor.yaml
input_boolean: !include input_boolean.yaml
script: !include scripts.yaml
